### ISSUE TITLE
Deprecation of Order status page additional scripts

### ISSUE THREAD

**Issue by liamgold** [Kentico/xperience-by-kentico-shopify#11]
**Is your feature request related to a problem? Please describe.**
Currently the [Usage Guide](https://github.com/Kentico/xperience-by-kentico-shopify/blob/main/docs/Usage-Guide.md) recommends to implement **Order status page additional scripts** for the order confirmation screen to redirect back to the XbyK site, with a thank you page.

The problem is that this approach of adding additional scripts to the confirmation screen is being deprecated, and ideally an alternative solution should be recommended. See the warning within Shopify:

![image](https://github.com/user-attachments/assets/6d591966-168f-4e03-aa83-92d84b31ffde)

**Describe the solution you'd like**
An alternative method of implementing a redirect back to the XbyK site. It sounds like either a Pixel or Custom App might be needed to handle the redirection

**Comment by DanielJurcaBS** [comment]
Hi Liam,
Thank you for bringing this to our attention. We will review possible alternative solutions and keep you updated.

**Comment by martinkyjac** [comment]
Hi Liam,
we are currently trying to find solution for this. Unfortunately, the web pixels did not work as we expected. The script runs inside separate iframe and redirects to another domains are not allowed there. Currently, we are communicating with support to resolve this issue as soon as possible.
