### ISSUE TITLE
Bug: Missing ability to clear/delete Shopify Settings in the admin portal

### ISSUE THREAD

**Issue by liamgold** [Kentico/xperience-by-kentico-shopify#12]
**Describe the bug**
If you configure the Shopify instance using the admin interface rather than appsettings.json or user secrets, then you can't delete/disable the configuration if you later want to switch to appsettings or user secrets.

![image](https://github.com/user-attachments/assets/6a037044-ff20-49f3-83e6-22992f7442b1)

I originally configured the admin settings interface as the appsettings in my project were not being loaded in.

**Comment by martinkyjac** [comment]
If you use the appsettings/user secrets configuration, the configuration from the admin interface will be ignored. Unfortunately, this is not currently mentioned in the documentation. We will add this information to both the documentation and the admin interface to make it clear.
