### ISSUE TITLE
Add discount coupon information to basket

### ISSUE THREAD

**Issue by liamgold** [Kentico/xperience-by-kentico-shopify#13]
**Is your feature request related to a problem? Please describe.**
Currently when you add a discount coupon to the basket, it shows the discount code and applies the discount.

However, you cannot tell what the discount is actually doing, it doesn't highlight which product(s) are being discounted, and doesn't highlight how much is being discounted.

It looks like this:
![image](https://github.com/user-attachments/assets/667d26ce-eba6-4438-b12b-304caccdf49a)

But when you get to the Shopify checkout page itself, you get a lot more information about the discount, you can see the amounts and which product(s) they're applied to.

![image](https://github.com/user-attachments/assets/3558cfbe-9d84-4075-924a-85a097f6839e)

**Describe the solution you'd like**
It would be great if the Basket reflected the Shopify Checkout screen.

**Comment by DanielJurcaBS** [comment]
Hi Liam,
Thank you for bringing this feature request to our attention. We will review it internally and keep you updated on any progress.
