### ISSUE TITLE
Shopify integration settings in appsettings.json ignored

### ISSUE THREAD

**Issue by liamgold** [Kentico/xperience-by-kentico-shopify#19]
**Describe the bug**
I'm still convinced that `CMSShopifyConfig` and `CMSShopifyWebsiteChannelsConfig` blocks inside the appsettings,json are being ignored. I mentioned this previously in [this issue](https://github.com/Kentico/xperience-by-kentico-shopify/issues/12#issue-2430861206).

I have the following in my website's appsettings.json

```
{
 ...

  "CMSShopifyConfig": {
    "ShopifyUrl": "https://example.myshopify.com/",
    "AdminApiToken": "shpat_code_here",
    "StorefrontApiToken": "shpat_code_here",
    "StorefrontApiVersion": "2024-04"
  },
  "CMSShopifyWebsiteChannelsConfig": {
    "Settings": [
      {
        "ChannelName": "Goldfinch",
        "CurrencyCode": "GBP",
        "Country": "GB"
      }
    ],
    "DefaultSetting": {
      "CurrencyCode": "GBP",
      "Country": "GB"
    }
  }
}
  ```

And every time the website tries to sync the products, the worker logs the following error:

```
Cannot start products synchronization. No Shopify integration settings provided.
```

**To Reproduce**
1. Follow instructions to set up the Shopify integration
2. Use the above appsettings block
3. Launch website

**Comment by martinkyjac** [comment]
Hi Liam,
We are working on resolving the issue and appreciate you bringing it to our attention. We will keep you updated.

**Comment by martinkyjac** [comment]
Hi Liam,
There's a mistake in the README. You should be using `AdminApiKey` instead of `AdminApiToken` and `StorefrontApiKey` instead of `StorefrontApiToken` in the `CMSShopifyConfig` appsettings section. Hope this helps and we'll update the README to reflect this.

**Comment by liamgold** [comment]
Thanks @martinkyjac - I've tested the changes on my local set up, and that does indeed fix it.
