### ISSUE TITLE
Fix: Code generation issues

### ISSUE THREAD

**Issue by seangwright** [Kentico/xperience-by-kentico-shopify#23]
**Describe the bug**

If a developer runs [code generation](https://docs.kentico.com/x/5IbWCQ) on a project that includes this Shopify integration, their code generation command will re-generate the Shopify content and custom object type classes that are _already_ included in the integration assemblies. This will cause their build to fail (if they use the same namespaces for this integration's object and content types) or it will cause runtime exceptions when calling `IContentQueryExecutor.GetMappedResult` or `IContentQueryExecutor.GetMappedWebPageResult` because the mapper will have 2 content types registered with the same name.

Other integrations avoid this issue by associating the custom object types with a `ResourceInfo` and marking that `ResourceInfo` [as not being in 'development' mode](https://github.com/Kentico/xperience-by-kentico-lucene/blob/v9.0.0/src/Kentico.Xperience.Lucene.Core/LuceneModuleInstaller.cs#L34). This will prevent the C# code files from being generated for any object types in this integration's assemblies. This is how Xperience by Kentico accomplishes the same result.

However, this won't resolve the issue with custom content types that are included in the package. Since Xperience treats all custom content types as belonging to the user of the product, there is no API to exclude ones coming from a 3rd party assembly.

Instead, these will need to be excluded with the `--exclude` flag in the code generation command. The docs for this integration should be updated to explain this will be required for anyone using the integration.

**To Reproduce**

1. Add the integration to an Xperience by Kentico project
2. Run [code generation](https://docs.kentico.com/x/5IbWCQ) on the project
3. Build the project
4. See compilation errors (if using the same namespaces)
5. Or... call `IContentQueryExecutor.GetMappedResult` or `IContentQueryExecutor.GetMappedWebPageResult` with the integration's content types and see a runtime exception

**Expected behavior**

After adding this integration, developers can re-generate their own project's C# code files and not experience any errors.

**Screenshots**
n/a

**Library Version**
All

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by liamgold** [comment]
Thank you for logging this, Sean. I'm open to discussing my example scenario further if needed. Before removing the generated files from my project, I was able to bypass the runtime error by using `IContentQueryExecutor.GetWebPageResult` (along with manual mapping using `IWebPageQueryResultMapper`) instead of `IContentQueryExecutor.GetMappedWebPageResult`.

I believe updating the documentation with the exclude flag would be very helpful - it would have saved me a lot of time going in circles, thinking I had broken something! 😂

**Comment by martinkyjac** [comment]
Hi Sean,
Thanks for pointing this out. We'll make the necessary updates to the docs.
